### ISSUE TITLE
Validate if diff() should be used in histogram

### ISSUE THREAD

**Issue by strangiato** [RedHatQuickCourses/rhods-qc-apps#21]
In the [data exploration notebook](https://github.com/RedHatQuickCourses/rhods-qc-apps/blob/main/3.create-model/pytorch-lab/notebooks/01-data-exploration.ipynb) it includes a step with the following code:

```python
# Plot histograms of the columns on multiple subplots
plt.close('all')
df.diff().hist(color="k", alpha=0.5, bins=20, figsize=(15, 10))
```

Which results in the following histogram:

![image](https://github.com/RedHatQuickCourses/rhods-qc-apps/assets/1628206/9fa51356-32fc-4b91-8570-e2efacbe6a0b)

There seems to be some confusion on if `diff()` should be included in the function as it generates some odd results including showing the distribution of data between -15 and 15 for pregnancies even though the data only contains results from 0-14.

We need to clarify if `diff()` is being used as a normalization technique to allow for easier review of the distribution of data, or if this is simply a mistake and `diff()` should be excluded from the histogram.  

If the `diff()` is intentional, some text should be added to include some explanation of why it is being used, and that it may produce some "un-intuitive" results, but that is expected to help avoid customer confusion.

**Comment by JeetRH** [comment]
Hey Trevor I removed the diff function and checked in the changes
