### ISSUE TITLE
Access denied accessing pytorch_model.bin

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-qc-apps#24]
The https://github.com/RedHatQuickCourses/rhods-qc-apps/blob/main/1.intro/chapter1/intro-text-generation/notebook.ipynb says

> Download the [pytorch_model.bin](https://drive.google.com/file/d/142H5pfiw7JKN29xv9rav1ZTDF2a8MCoZ/view?usp=sharing) from Google Drive file into your computer.

However, acessing that Google Driver URL yields

Access denied
You need access
Request access, or switch to an account with access.

I don't think that people should have to ask for access to a mandatory part of the https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter2/section4.html (a.k.a. https://start.learning.redhat.com/totara/5400) course.

**Comment by rsriniva** [comment]
@adelton - are you accessing the google drive with your redhat google account? I believe we have sharing set to read-only for all redhat associates. We had to resort to storing this large 312MB file in gdrive because we didn't want to store it in git

**Comment by jramcast** [comment]
Moved file to a GH release: https://github.com/RedHatQuickCourses/rhods-qc-apps/pull/27

**Comment by rsriniva** [comment]
PR #27 submitted by the awesome @jramcast to fix this. We now host the large model file in github releases. A hacky solution, but hopefully fixes the access issue
