### ISSUE TITLE
creditcard.csv doesn't exist in minio bucket and there isn't any step to add it

### ISSUE THREAD

**Issue by aokugel** [RedHatQuickCourses/rhods-qc-apps#30]
https://github.com/RedHatQuickCourses/rhods-qc-apps/blob/main/7.hands-on-lab/README.md?plain=1#L29
https://github.com/RedHatQuickCourses/rhods-qc-apps/blob/main/7.hands-on-lab/README.md?plain=1#L55

Is `creditcard.csv` supposed to be the dataset referenced here? 
https://github.com/RedHatQuickCourses/rhods-pipelines/blob/main/modules/chapter1/pages/elyra-pipelines.adoc?plain=1#L64

it's named `live-data.csv` and i don't see any instruction to rename it.

**Comment by rsriniva** [comment]
yes. it's the same thing.

**Comment by aokugel** [comment]
@rsriniva I believe that the creditcard.csv file mentioned in #31 is missing a field "class" which is a boolean value that states whether the given credit card transaction is actual fraud.  I'm getting the following key error when running `2.exploration.ipynb` as part of the final lab:

```
KeyError: 'Class'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[9], line 2
      1 print(
----> 2     f"No Frauds {round(df['Class'].value_counts()[0]/len(df) * 100, 2)}"
      3     f' % of the dataset'
      4 )
      5 print(
      6     f"Frauds {round(df['Class'].value_counts()[1]/len(df) * 100, 2)}"
      7     f'% of the dataset'
      8 )

```
